[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlink.x"]

[env]
EMU_TICK_RATE = "100"

[alias]
rbuild = "build --release --target riscv32i-unknown-none-elf"
rb = "rbuild"

rdoc = "doc --release --target riscv32i-unknown-none-elf"
rd = "rdoc"

rsize = "size --release --target riscv32i-unknown-none-elf"
rs = "rsize"

robjdump = "objdump --release --target riscv32i-unknown-none-elf"
rod = "robjdump"

