[target.riscv32i-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlink.x"]

[build]
target = "riscv32i-unknown-none-elf"
# target = "riscv32imac-unknown-none-elf"
# target = "riscv32imc-unknown-none-elf"


